script:
  - "make test"

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"

branches:
  only:
    - master
    - dev
    - /^greenkeeper/.*$/

matrix:
  fast_finish: true
  include:
    - node_js: "0.10"
      env: COVERAGE=true
  allow_failures:
    - env: COVERAGE=true

sudo: false
